### ISSUE TITLE
Tab vs. spaces and maximum indent issues

### ISSUE THREAD

**Issue by sdether** [brianc/jade-mode#1]
Not sure if it's an emacs config issue or jade-mode issue.

First should jade mode be using tabs or spaces. I noticed that my space indented files should all element names in red, but even your example.jade mixes spaces and tabs.

Second while Shift-Tab works great, Tab always only indents to the very first level and with leading # inserts a space, i.e. in the example.jade file if i hit tab at the beginning of the #container line i get this

```
    #container
^
```
[tab]

```
    #container
     ^
```
[tab]

```
#container
^
```
[tab]

```
  #container
  ^
```
[tab]

```
  #container
   ^
```
[tab]

```
  # container
    ^
```

And after that all the [tab] hitting will not move it further

**Comment by tjefferson08** [comment]
So OLD! Closing as stale/fixed, please reopen if you can still reproduce the issue.
