### ISSUE TITLE
Unindented Tag Text Not Highlighting

### ISSUE THREAD

**Issue by eethann** [brianc/jade-mode#13]
I'm having an issue with a jade docpad document file, basically a partial.  All elements after the first level are highlighted correctly, however the first level elements (in this case "section" tags) are not highlighted.

An example section of the file is:

```jade
section.slide
  h2 Other supported entities:
  ul
    li comments
    li users
    li taxonomy terms
```

The `h2`, `ul` and `li` elements are all highlighted.  The initial `section` element is not, though a class or id element appended to the section tag is colored correctly.

I'm running the latest MELPA version (20120730) and Emacs 24.

**Comment by tjefferson08** [comment]
This looks pretty fixed to me! Closing time!
