### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by zobi8225** [brianc/jade-mode#15]
Hi, i have seen there are jade-mode in marmalade repo.  (http://marmalade-repo.org/packages/jade-mode)
It is written, marmalade use the 0.1 version of jade-mode.

But i don't know witch version is use on github . Perhaps we could creat a file or anything to indicate the github version.

(Sorry for my bad english)

**Comment by tjefferson08** [comment]
I'd recommend using the version on [melpa](http://melpa.org/#/jade-mode)! 

With that, closing this issue :)
