### ISSUE TITLE
Backtabbing highlighted text hangs emacs (Jade-mode)

### ISSUE THREAD

**Issue by ProjectFrank** [brianc/jade-mode#27]
Running Emacs 24.3.92.1

**Comment by tjefferson08** [comment]
+1, it looks like the bug is reproducible in sws-mode, from which jade-mode is derived. I'm working on a fix (by removing the dependency on sws-mode and writing custom indentation functions)

**Comment by Sterlingg** [comment]
I've made PR #28 to fix the original indent function in the meantime, while @tjefferson08 redoes the indentation functions

**Comment by tjefferson08** [comment]
Fixed in PR #30, let's close this sucka!
