### ISSUE TITLE
Melpa stable

### ISSUE THREAD

**Issue by nlamirault** [brianc/jade-mode#29]
could you please create a tag to use this package using melpa stable [1].
Thanks

[1] : http://stable.melpa.org/

**Comment by brianc** [comment]
I'd love to - how do I do that?

**Comment by nlamirault** [comment]
By creating tags.

**Comment by tjefferson08** [comment]
Just tagged v1.0.0, I'll close the issue when I see it on the stable list.

**Comment by nlamirault** [comment]
It's available. See [1].
Thanks.

[1]: http://stable.melpa.org/#/jade-mode
